"""prices date modified

Revision ID: 069f6b3ed651
Revises: fbddce016382
Create Date: 2025-04-14 15:22:23.987225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '069f6b3ed651'
down_revision: Union[str, None] = 'fbddce016382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('market_date', sa.Date(), nullable=False))
    op.drop_index('ix_prices_date', table_name='prices')
    op.create_index(op.f('ix_prices_market_date'), 'prices', ['market_date'], unique=False)
    op.drop_column('prices', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_prices_market_date'), table_name='prices')
    op.create_index('ix_prices_date', 'prices', ['date'], unique=False)
    op.drop_column('prices', 'market_date')
    # ### end Alembic commands ###
