"""prices currency added

Revision ID: 43c1c1ffaa3d
Revises: 069f6b3ed651
Create Date: 2025-04-15 15:28:47.138025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c1c1ffaa3d'
down_revision: Union[str, None] = '069f6b3ed651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE currencyenum AS ENUM ('USD', 'EUR', 'JPY', 'GBP', 'AUD', 'CAD', 'CHF', 'CNY', 'HKD', 'NZD', 'SEK', 'SGD', 'NOK', 'MXN')")
    op.add_column('prices', sa.Column('currency', sa.Enum('USD', 'EUR', 'JPY', 'GBP', 'AUD', 'CAD', 'CHF', 'CNY', 'HKD', 'NZD', 'SEK', 'SGD', 'NOK', 'MXN', name='currencyenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'currency')
    op.execute("DROP TYPE currencyenum")
    # ### end Alembic commands ###
