"""regenerate database from scratch

Revision ID: 556f32f91d39
Revises: 
Create Date: 2025-04-23 13:04:11.617212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556f32f91d39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('sector', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('company_ticker', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('buy', 'sell', name='typeenum'), nullable=False),
    sa.ForeignKeyConstraint(['company_ticker'], ['companies.ticker'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_company_ticker'), 'positions', ['company_ticker'], unique=False)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=True)
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_table('prices',
    sa.Column('company_ticker', sa.String(length=10), nullable=False),
    sa.Column('market_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'JPY', 'GBP', 'AUD', 'CAD', 'CHF', 'CNY', 'HKD', 'NZD', 'SEK', 'SGD', 'NOK', 'MXN', name='currencyenum'), nullable=False),
    sa.ForeignKeyConstraint(['company_ticker'], ['companies.ticker'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_ticker', 'market_date')
    )
    op.create_index(op.f('ix_prices_company_ticker'), 'prices', ['company_ticker'], unique=False)
    op.create_index(op.f('ix_prices_market_date'), 'prices', ['market_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_market_date'), table_name='prices')
    op.drop_index(op.f('ix_prices_company_ticker'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_company_ticker'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
