"""patched model for prices

Revision ID: fbddce016382
Revises: 7bffb412de06
Create Date: 2025-04-14 02:01:32.738382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbddce016382'
down_revision: Union[str, None] = '7bffb412de06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_ticker', table_name='prices')
    op.drop_column('prices', 'volume')
    op.drop_column('prices', 'open')
    op.drop_column('prices', 'low')
    op.drop_column('prices', 'ticker')
    op.drop_column('prices', 'high')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('prices', sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('prices', sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('prices', sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('prices', sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_prices_ticker', 'prices', ['ticker'], unique=False)
    # ### end Alembic commands ###
